import type { TranslationErrorCode, UiLanguage } from '../domain/types'

type CopyParams = Record<string, number | string>
type CopyValue = string | ((params: CopyParams) => string)

const COPY: Record<UiLanguage, Record<string, CopyValue>> = {
  'zh-CN': {
    appName: 'ReadFlow',
    preparingTitle: '正在准备文档...',
    preparingBody: '正在解析本地内容、恢复阅读上下文并加载已缓存的真实译文。',
    openErrorTitle: '无法打开这个文档。',
    backToLibrary: '返回书库',
    back: '返回',
    library: '书库',
    more: '更多',
    openLibrary: '打开书库',
    deleteDocument: '删除文档',
    deleteDocumentConfirm: '删除这个文档及其全部本地阅读数据吗？',
    original: 'Original',
    translation: 'Translation',
    uiChinese: '中文',
    uiEnglish: 'EN',
    languageSwitchLabel: '界面语言',
    currentDocument: '当前文档',
    untitledDocument: '未命名文档',
    paragraphCountMeta: ({ paragraphCount, pageCount }) => `${paragraphCount} 个段落 | ${pageCount} 页`,
    cached: '已缓存',
    availableOffline: '可离线阅读',
    structure: 'Structure',
    myStudy: 'My Study',
    details: 'Details',
    highlights: 'Highlights',
    tags: 'Tags',
    recentlyRead: 'Recently Read',
    highlightsEmpty: '还没有高亮。',
    highlightsReviewMeta: '回看已保存高亮，并跳回原文位置。',
    tagsEmpty: '还没有标签。',
    tagsReviewMeta: '按标签查看关联高亮并回到正文。',
    recentlyReadEmpty: '还没有保存的阅读位置。',
    readerTools: '阅读工具',
    readerToolsCopy: '先保持阅读流，再按需打开结构导航、学习沉淀或当前段落详情。',
    readerToolsStructureMeta: '在不把控件压到正文前面的前提下，快速跳转文档结构。',
    readerToolsStudyMeta: '查看当前文档的高亮、标签和最近阅读锚点。',
    readerToolsNotesMeta: '查看和编辑从句子创建的学习笔记。',
    readerToolsDetailsMeta: '查看当前段落状态、翻译摘要和局部高亮上下文。',
    close: '关闭',
    currentParagraph: '当前段落',
    noParagraphSelected: '当前没有选中段落',
    noParagraphInView: '当前没有可见段落',
    scrollForParagraphDetails: '滚动到任一段落即可加载详情。',
    paragraphTitle: ({ order, page }) => `段落 ${order} | 第 ${page} 页`,
    paragraphLabel: ({ page, order, total }) => `第 ${page} 页 | 段落 ${order}/${total}`,
    paragraphLabelCompact: ({ page, order }) => `P${page} · 段落 ${order}`,
    structurePageLabel: ({ page }) => `第 ${page} 页`,
    structureParagraphSingle: ({ start }) => `段落 ${start}`,
    structureParagraphRange: ({ start, end }) => `段落 ${start}-${end}`,
    structureReadingUnits: ({ count }) => `${count} 个阅读单元`,
    unknownParagraph: '未知段落',
    translationStatus: '翻译状态',
    translationCachedVia: ({ provider }) => `真实译文已缓存 · ${provider}`,
    translationLoadingCurrent: '正在获取当前段落的真实译文。',
    translationLoadingAround: '将围绕当前可见段落尝试获取真实译文。',
    translationFailedDefault: '真实翻译失败。',
    translationUnavailableInline: '未接入真实翻译服务。',
    translationServiceUnavailable: '当前未接入真实翻译服务，译文模式不会展示假翻译。',
    retryTranslation: '重试翻译',
    highlightsAndTags: '高亮与标签',
    openMyStudy: '打开 My Study',
    notes: 'Notes',
    notesReviewBody: '查看当前文档中从句子创建的全部学习笔记。',
    notesEmpty: '当前文档还没有学习笔记。',
    showNotes: '显示笔记',
    hideNotes: '隐藏笔记',
    addToNotes: '加入笔记',
    highlightParagraph: '高亮段落',
    removeParagraphHighlight: '取消段落高亮',
    editTags: '编辑标签',
    noTagsYet: '暂无标签',
    noHighlightsInParagraph: '当前段落还没有高亮。',
    highlightsReviewTitle: '高亮回看',
    highlightsReviewBody: '查看当前文档中的全部高亮并跳回原文。',
    tagsReviewTitle: '标签回看',
    tagsReviewBody: '打开标签并查看该标签下的高亮。',
    recentReviewTitle: '最近阅读',
    recentReviewBody: '返回当前文档上次保存的阅读锚点。',
    savedAnchor: '已保存锚点',
    noHighlightsForDocument: '当前文档还没有保存高亮。',
    noTagsForDocument: '当前文档还没有保存标签。',
    noHighlightsLinkedToTag: '这个标签下还没有关联高亮。',
    sentenceHighlightLabel: '句子高亮',
    paragraphHighlightLabel: '段落高亮',
    searchParagraphs: '搜索段落',
    searchAction: '搜索',
    addTag: '添加标签',
    saveTag: '保存标签',
    highlightAction: '高亮',
    removeHighlightAction: '取消高亮',
    addTagShort: '加标签',
    copy: '复制',
    cacheShort: '缓存',
    savedLocalShort: '本地',
    savedLocally: '已保存到本地',
    offlineUnavailable: '离线不可用',
    offlineOff: '离线关闭',
    offlinePartial: '离线部分可用',
    offlineLimited: '离线受限',
    offlineReady: '离线可用',
    offlineNow: '离线中',
    documentNotCachedYet: '当前文档还没有完成本地缓存。',
    translationSavedOffline: '这条真实译文已经保存到本地，离线时也可重新打开。',
    translationRetryWhenReady: '当前是真实翻译失败，可在准备好后再次重试。',
    translationReconnectToRetry: '重新联网后可重试并缓存这条真实译文。',
    translationNotCachedReconnect: '这条真实译文尚未缓存，需联网后获取。',
    translationWillBeCached: '真实译文加载成功后会写入本地缓存。',
    restoredToParagraph: ({ paragraph }) => `已恢复到第 ${paragraph} 段。`,
    returnedToReadingAnchor: ({ summary }) => `已返回 ${summary}。`,
    noSavedReadingPosition: '还没有保存的阅读位置。',
    noParagraphMatchedSearch: '没有匹配到段落。',
    jumpedToParagraph: ({ paragraph }) => `已跳转到第 ${paragraph} 段。`,
    sentenceHighlightAdded: '已高亮句子。',
    sentenceHighlightRemoved: '已取消句子高亮。',
    paragraphHighlightAdded: '已高亮段落。',
    paragraphHighlightRemoved: '已取消段落高亮。',
    tagAddedToSentence: ({ name }) => `已为选中句子添加标签“${name}”。`,
    tagAddedToParagraph: ({ name }) => `已为当前段落添加标签“${name}”。`,
    sentenceCopied: '已复制句子。',
    copyUnavailable: '当前浏览器环境不支持复制。',
    translationRetried: '已重新请求当前段落的真实翻译。',
    loadErrorMissingDocument: '本地没有找到这个文档。',
    loadErrorMissingFile: '本地 PDF 文件缺失，无法重新解析。',
    loadErrorFallback: '打开文档失败。',
    translationErrorOffline: '当前离线，且这段还没有缓存过真实译文。',
    translationErrorRequestFailed: '真实翻译请求失败。',
    translationErrorEmptyResult: '真实翻译服务返回了空结果。',
    translationErrorProviderNotConfigured: '当前未配置真实翻译服务。',
    translationErrorUnknown: '真实翻译失败。',
    readingFragment: '阅读片段',
    fullSentence: '完整句',
    showFullSentence: '查看整句',
    showFragment: '只看片段',
    sentenceCardOriginal: '原文',
    sentenceCardTranslation: '当前理解',
    highlightColors: '高亮颜色',
    existingTags: '已有标签',
    newTagOptional: '新建标签（可选）',
    phoneticLabel: '音标',
    pronunciationLabel: '发音',
    meaningInSentence: '当前句义',
    phoneticUnavailable: '当前构建未提供音标数据',
    pronunciationUnavailable: '当前环境不支持发音',
    wordMeaningUnavailable: '当前片段还没有可用译文。',
    playPronunciation: '发音',
    savedToDevice: '已保存到本机',
    notSavedYet: '当前内容还没保存到本机',
    originalOfflineReady: '当前原文可离线阅读',
    translationOfflineReady: '当前译文可离线阅读',
    translationNotCachedYet: '当前译文还没离线保存',
    translationOfflineUnavailable: '当前译文离线不可用',
    translationUnavailableStatus: '当前译文需要真实翻译服务',
    translationLoadingStatus: '当前译文正在加载',
    translationFailedStatus: '当前译文加载失败，可重试',
    retrySentenceTranslation: '重试句子翻译',
    sentenceTranslationRetried: '已重新请求句子翻译。',
    wordLookupLoading: '正在查询词义...',
    wordLookupFailed: '查词失败，可重试。',
    wordLookupUnavailable: '未配置翻译服务，无法查词。',
    retryWordLookup: '重试查词',
    wordDefinition: '词义',
    saveToVocab: '收藏单词',
    wordSavedToVocab: '已收藏到单词本。',
    wordRemovedFromVocab: '已从单词本移除。',
    removeFromVocab: '取消收藏',
    vocab: '单词本',
    vocabEmpty: '还没有收藏的单词。',
    vocabDeleteEntry: '删除',
    vocabEntryFrom: ({ title }) => `来源：${title}`,
    exportHighlights: '导出摘录',
    exportAsMarkdown: '导出为 Markdown',
    exportAsTxt: '导出为 TXT',
    exportAllHighlights: '导出全部高亮',
    exportByTag: ({ name }) => `按标签"${name}"导出`,
    exportDone: '已导出摘录文件。',
    noHighlightsToExport: '当前文档没有可导出的高亮。'
  },
  en: {
    appName: 'ReadFlow',
    preparingTitle: 'Preparing your document...',
    preparingBody: 'Parsing local content, restoring reading context, and loading cached live translations.',
    openErrorTitle: 'We could not open this document.',
    backToLibrary: 'Back to library',
    back: 'Back',
    library: 'Library',
    more: 'More',
    openLibrary: 'Open library',
    deleteDocument: 'Delete document',
    deleteDocumentConfirm: 'Delete this document and all local reading data?',
    original: 'Original',
    translation: 'Translation',
    uiChinese: '中文',
    uiEnglish: 'EN',
    languageSwitchLabel: 'UI language',
    currentDocument: 'Current document',
    untitledDocument: 'Untitled document',
    paragraphCountMeta: ({ paragraphCount, pageCount }) => `${paragraphCount} paragraphs | ${pageCount} pages`,
    cached: 'Cached',
    availableOffline: 'Available offline',
    structure: 'Structure',
    myStudy: 'My Study',
    details: 'Details',
    highlights: 'Highlights',
    tags: 'Tags',
    recentlyRead: 'Recently Read',
    highlightsEmpty: 'No highlights yet.',
    highlightsReviewMeta: 'Review saved highlights and jump back into the text.',
    tagsEmpty: 'No tags yet.',
    tagsReviewMeta: 'Open tag groups and revisit linked highlights.',
    recentlyReadEmpty: 'No saved reading position yet.',
    readerTools: 'Reader tools',
    readerToolsCopy: 'Keep reading first, then open structure, study review, or current paragraph details when needed.',
    readerToolsStructureMeta: 'Jump through the document structure without pinning controls above the text.',
    readerToolsStudyMeta: 'Review highlights, tags, and the saved reading anchor for this document.',
    readerToolsNotesMeta: 'Review and edit study notes created from sentences.',
    readerToolsDetailsMeta: 'See the current paragraph status, translation summary, and local highlight context.',
    close: 'Close',
    currentParagraph: 'Current paragraph',
    noParagraphSelected: 'No paragraph selected',
    noParagraphInView: 'No paragraph in view',
    scrollForParagraphDetails: 'Scroll to a paragraph to load its details.',
    paragraphTitle: ({ order, page }) => `Paragraph ${order} | Page ${page}`,
    paragraphLabel: ({ page, order, total }) => `Page ${page} | Paragraph ${order}/${total}`,
    paragraphLabelCompact: ({ page, order }) => `P${page} · Paragraph ${order}`,
    structurePageLabel: ({ page }) => `Page ${page}`,
    structureParagraphSingle: ({ start }) => `Paragraph ${start}`,
    structureParagraphRange: ({ start, end }) => `Paragraphs ${start}-${end}`,
    structureReadingUnits: ({ count }) => `${count} reading unit${count === 1 ? '' : 's'}`,
    unknownParagraph: 'Unknown paragraph',
    translationStatus: 'Translation status',
    translationCachedVia: ({ provider }) => `Live translation cached via ${provider}`,
    translationLoadingCurrent: 'Loading a live translation for the current paragraph.',
    translationLoadingAround: 'Live translation will load around the visible paragraph.',
    translationFailedDefault: 'Live translation failed.',
    translationUnavailableInline: 'No live translation provider is configured.',
    translationServiceUnavailable: 'No live translation provider is configured, so Translation mode will not show fallback text.',
    retryTranslation: 'Retry translation',
    highlightsAndTags: 'Highlights and tags',
    openMyStudy: 'Open My Study',
    notes: 'Notes',
    notesReviewBody: 'Review all study notes created from sentences in this document.',
    notesEmpty: 'No study notes saved for this document yet.',
    showNotes: 'Show notes',
    hideNotes: 'Hide notes',
    addToNotes: 'Add note',
    highlightParagraph: 'Highlight paragraph',
    removeParagraphHighlight: 'Remove paragraph highlight',
    editTags: 'Edit tags',
    noTagsYet: 'No tags yet',
    noHighlightsInParagraph: 'No highlights in this paragraph yet.',
    highlightsReviewTitle: 'Highlights',
    highlightsReviewBody: 'Review all saved highlights for this document and jump back into the original text.',
    tagsReviewTitle: 'Tags',
    tagsReviewBody: 'Open a tag to review the linked highlights in this document.',
    recentReviewTitle: 'Recently read',
    recentReviewBody: 'Return to the last saved paragraph anchor for this document.',
    savedAnchor: 'Saved anchor',
    noHighlightsForDocument: 'No highlights saved for this document yet.',
    noTagsForDocument: 'No tags saved for this document yet.',
    noHighlightsLinkedToTag: 'No highlights linked to this tag yet.',
    sentenceHighlightLabel: 'Sentence highlight',
    paragraphHighlightLabel: 'Paragraph highlight',
    searchParagraphs: 'Search paragraphs',
    searchAction: 'Search',
    addTag: 'Add tag',
    saveTag: 'Save tag',
    highlightAction: 'Highlight',
    removeHighlightAction: 'Remove highlight',
    addTagShort: 'Add tag',
    copy: 'Copy',
    cacheShort: 'Cache',
    savedLocalShort: 'Local',
    savedLocally: 'Saved locally',
    offlineUnavailable: 'Offline unavailable',
    offlineOff: 'Offline off',
    offlinePartial: 'Offline partial',
    offlineLimited: 'Offline limited',
    offlineReady: 'Offline ready',
    offlineNow: 'Offline now',
    documentNotCachedYet: 'This document has not finished caching locally yet.',
    translationSavedOffline: 'This live translation is saved locally and can be reopened offline.',
    translationRetryWhenReady: 'This live translation failed. Retry whenever you are ready.',
    translationReconnectToRetry: 'Reconnect to retry and cache this live translation.',
    translationNotCachedReconnect: 'This live translation is not cached yet. Reconnect to load it.',
    translationWillBeCached: 'The live translation will be cached after it loads.',
    restoredToParagraph: ({ paragraph }) => `Restored to paragraph ${paragraph}.`,
    returnedToReadingAnchor: ({ summary }) => `Returned to ${summary}.`,
    noSavedReadingPosition: 'No saved reading position yet.',
    noParagraphMatchedSearch: 'No paragraph matched this search.',
    jumpedToParagraph: ({ paragraph }) => `Jumped to paragraph ${paragraph}.`,
    sentenceHighlightAdded: 'Sentence highlighted.',
    sentenceHighlightRemoved: 'Sentence highlight removed.',
    paragraphHighlightAdded: 'Paragraph highlighted.',
    paragraphHighlightRemoved: 'Paragraph highlight removed.',
    tagAddedToSentence: ({ name }) => `Added tag "${name}" to the selected sentence.`,
    tagAddedToParagraph: ({ name }) => `Added tag "${name}" to the current paragraph.`,
    sentenceCopied: 'Sentence copied.',
    copyUnavailable: 'Copy is not available in this browser context.',
    translationRetried: 'Retried the live translation for the current paragraph.',
    loadErrorMissingDocument: 'This document was not found locally.',
    loadErrorMissingFile: 'The local PDF file is missing, so the document cannot be parsed.',
    loadErrorFallback: 'Failed to open this document.',
    translationErrorOffline: 'You are offline and this paragraph does not have a cached live translation yet.',
    translationErrorRequestFailed: 'The live translation request failed.',
    translationErrorEmptyResult: 'The live translation provider returned an empty result.',
    translationErrorProviderNotConfigured: 'No live translation provider is configured.',
    translationErrorUnknown: 'Live translation failed.',
    readingFragment: 'Reading fragment',
    fullSentence: 'Full sentence',
    showFullSentence: 'Show full sentence',
    showFragment: 'Show fragment',
    sentenceCardOriginal: 'Original',
    sentenceCardTranslation: 'Meaning here',
    highlightColors: 'Highlight colors',
    existingTags: 'Existing tags',
    newTagOptional: 'Create a tag (optional)',
    phoneticLabel: 'Phonetic',
    pronunciationLabel: 'Pronunciation',
    meaningInSentence: 'Meaning in this sentence',
    phoneticUnavailable: 'No phonetic data is available in this build.',
    pronunciationUnavailable: 'Pronunciation is not available in this environment.',
    wordMeaningUnavailable: 'No translated context is available for this fragment yet.',
    playPronunciation: 'Pronounce',
    savedToDevice: 'Saved to this device',
    notSavedYet: 'This content is not saved on this device yet',
    originalOfflineReady: 'The current original text is ready offline',
    translationOfflineReady: 'The current translation is ready offline',
    translationNotCachedYet: 'The current translation is not saved offline yet',
    translationOfflineUnavailable: 'The current translation is unavailable offline',
    translationUnavailableStatus: 'A live translation service is still required',
    translationLoadingStatus: 'The current translation is loading',
    translationFailedStatus: 'The current translation failed and can be retried',
    retrySentenceTranslation: 'Retry sentence translation',
    sentenceTranslationRetried: 'Retried the sentence translation.',
    wordLookupLoading: 'Looking up word meaning...',
    wordLookupFailed: 'Word lookup failed. Tap to retry.',
    wordLookupUnavailable: 'No translation provider is configured for word lookup.',
    retryWordLookup: 'Retry lookup',
    wordDefinition: 'Definition',
    saveToVocab: 'Save word',
    wordSavedToVocab: 'Word saved to vocabulary.',
    wordRemovedFromVocab: 'Word removed from vocabulary.',
    removeFromVocab: 'Remove from vocabulary',
    vocab: 'Vocabulary',
    vocabEmpty: 'No words saved yet.',
    vocabDeleteEntry: 'Delete',
    vocabEntryFrom: ({ title }) => `From: ${title}`,
    exportHighlights: 'Export excerpts',
    exportAsMarkdown: 'Export as Markdown',
    exportAsTxt: 'Export as TXT',
    exportAllHighlights: 'Export all highlights',
    exportByTag: ({ name }) => `Export by tag "${name}"`,
    exportDone: 'Excerpt file exported.',
    noHighlightsToExport: 'No highlights to export for this document.'
  }
}

function interpolate(template: string, params: CopyParams): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? ''))
}

export function getReaderCopy(language: UiLanguage, key: string, params: CopyParams = {}): string {
  const entry = COPY[language][key] ?? COPY.en[key] ?? key
  if (typeof entry === 'function') {
    return entry(params)
  }

  return interpolate(entry, params)
}

export function getTranslationErrorCopy(language: UiLanguage, errorCode: TranslationErrorCode, fallbackMessage?: string | null): string {
  if (errorCode === 'offline') {
    return getReaderCopy(language, 'translationErrorOffline')
  }

  if (errorCode === 'request_failed') {
    return getReaderCopy(language, 'translationErrorRequestFailed')
  }

  if (errorCode === 'empty_result') {
    return getReaderCopy(language, 'translationErrorEmptyResult')
  }

  if (errorCode === 'provider_not_configured') {
    return getReaderCopy(language, 'translationErrorProviderNotConfigured')
  }

  return fallbackMessage?.trim() || getReaderCopy(language, 'translationErrorUnknown')
}

export function localizeReaderLoadError(language: UiLanguage, message: string): string {
  if (message === 'This document was not found locally.') {
    return getReaderCopy(language, 'loadErrorMissingDocument')
  }

  if (message === 'The local PDF file is missing, so the document cannot be parsed.') {
    return getReaderCopy(language, 'loadErrorMissingFile')
  }

  return message || getReaderCopy(language, 'loadErrorFallback')
}
